// Generated by scripts/generate-protocol.py. Do not edit by hand.

export type JsonRpcId = string | number | null;

export interface JsonRpcErrorObject {
  code: number;
  message: string;
  data?: unknown | null;
}

export interface JsonRpcRequest {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: Record<string, unknown> | null;
}

export interface JsonRpcNotification {
  jsonrpc?: "2.0";
  method: string;
  params?: Record<string, unknown> | null;
}

export interface JsonRpcResponse {
  jsonrpc?: "2.0";
  id?: string | number | null;
  result?: unknown | null;
  error?: JsonRpcErrorObject | null;
}

export interface WorkspaceRecord {
  id: string;
  repo_path: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectRecord {
  id: string;
  workspace_id: string;
  title: string;
  objective: string;
  research_context: string;
  status: "active" | "closed";
  created_at: string;
  updated_at: string;
}

export interface SessionRecord {
  id: string;
  workspace_id: string;
  project_id?: string | null;
  status: "active" | "closed";
  created_at: string;
  updated_at: string;
}

export interface HypothesisRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  title: string;
  summary: string;
  status: "triage" | "accepted" | "active" | "in_review" | "done" | "canceled" | "failed";
  created_at: string;
  updated_at: string;
}

export interface ExperimentRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  status: "triage" | "accepted" | "active" | "in_review" | "done" | "canceled" | "failed";
  title: string;
  summary: string;
  worktree_path?: string | null;
  base_commit?: string | null;
  candidate_commit?: string | null;
  parent_experiment_id?: string | null;
  research_thread?: string | null;
  created_at: string;
  updated_at: string;
}

export interface BaselineRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  status: "triage" | "accepted" | "active" | "in_review" | "done" | "canceled" | "failed";
  title: string;
  summary: string;
  created_at: string;
  updated_at: string;
}

export interface EvaluationRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  status: "triage" | "accepted" | "active" | "in_review" | "done" | "canceled" | "failed";
  title: string;
  summary: string;
  associated_baseline_id?: string | null;
  associated_experiment_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface MetricValue {
  value: boolean | number | string;
  unit?: string | null;
  direction?: "higher_is_better" | "lower_is_better" | "target" | "informational";
  notes?: string | null;
}

export interface MeasurementPayload {
  activity_type?: string | null;
  measurement_type?: string | null;
  summary?: string | null;
  command?: string | null;
  workspace_state?: Record<string, unknown> | null;
  metrics?: Record<string, MetricValue>;
  raw_output_summary?: string | null;
  artifact_ids?: string[];
  comparison_baseline_id?: string | null;
  comparison_measurement_id?: string | null;
  comparison_metric_deltas?: Record<string, MetricValue>;
  [key: string]: unknown;
}

export interface MeasurementRecord {
  id: string;
  evaluation_id: string;
  created_in_session_id?: string | null;
  actor: string;
  body: string;
  payload?: MeasurementPayload;
  created_at: string;
}

export interface AnalysisRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  created_by_agent_id?: string | null;
  status: "triage" | "accepted" | "active" | "in_review" | "done" | "canceled" | "failed";
  title: string;
  summary: string;
  content: string;
  supersedes_analysis_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface HypothesisExperimentLinkRecord {
  hypothesis_id: string;
  experiment_id: string;
  created_at: string;
}

export interface AgentRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  kind: "manager" | "researcher" | "scientist" | "critic";
  display_name: string;
  model_name?: string | null;
  status: "idle" | "active" | "closed";
  created_at: string;
  updated_at: string;
}

export interface TaskRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  title: string;
  content: string;
  kind: "plan" | "research" | "baseline" | "hypothesize" | "experiment" | "interpret";
  work_type?: string | null;
  status: "triage" | "backlog" | "in_progress" | "done" | "canceled" | "failed";
  priority: "urgent" | "high" | "normal" | "low";
  source_kind: "manager" | "user" | "system";
  assignee_id?: string | null;
  parent_task_id?: string | null;
  payload?: Record<string, unknown>;
  pydantic_run_id?: string | null;
  conversation_id?: string | null;
  result_summary?: string | null;
  workflow_id?: string | null;
  created_at: string;
  available_at: string;
  claimed_in_session_id?: string | null;
  claimed_at?: string | null;
  completed_in_session_id?: string | null;
  completed_at?: string | null;
  updated_at: string;
}

export interface TaskDependencyRecord {
  project_id: string;
  task_id: string;
  blocked_by_task_id: string;
  created_at: string;
}

export interface TaskEntityLinkRecord {
  project_id: string;
  task_id: string;
  entity_kind: "analysis" | "baseline" | "hypothesis" | "experiment" | "evaluation" | "measurement" | "artifact" | "analysis_activity" | "hypothesis_activity" | "experiment_activity" | "evaluation_activity" | "task_activity" | "event";
  entity_id: string;
  relationship: string;
  created_at: string;
}

export interface TaskActivityRecord {
  id: number;
  project_id: string;
  task_id: string;
  created_in_session_id?: string | null;
  actor_agent_id?: string | null;
  actor: string;
  kind: "created" | "updated" | "status_updated" | "recorded" | "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface AnalysisActivityRecord {
  id: number;
  analysis_id: string;
  created_in_session_id?: string | null;
  actor: string;
  kind: "created" | "updated" | "status_updated" | "recorded" | "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface HypothesisActivityRecord {
  id: number;
  hypothesis_id: string;
  created_in_session_id?: string | null;
  actor: string;
  kind: "created" | "updated" | "status_updated" | "recorded" | "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface BaselineActivityRecord {
  id: number;
  baseline_id: string;
  created_in_session_id?: string | null;
  actor: string;
  kind: "created" | "updated" | "status_updated" | "recorded" | "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface ExperimentActivityRecord {
  id: number;
  experiment_id: string;
  created_in_session_id?: string | null;
  actor: string;
  kind: "created" | "updated" | "status_updated" | "recorded" | "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface EvaluationActivityRecord {
  id: number;
  evaluation_id: string;
  created_in_session_id?: string | null;
  actor: string;
  kind: "created" | "updated" | "status_updated" | "recorded" | "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface ArtifactReadParams {
  artifact_id: string;
}

export interface ArtifactReadResult {
  artifact_id: string;
  media_type?: string | null;
  size_bytes?: number | null;
  content: string;
  truncated?: boolean;
  truncated_at_bytes?: number | null;
}

export interface ArtifactRecord {
  id: string;
  project_id: string;
  created_in_session_id?: string | null;
  associated_entity_kind: string;
  associated_entity_id: string;
  kind: string;
  title: string;
  path: string;
  media_type?: string | null;
  size_bytes?: number | null;
  created_at: string;
}

export interface EventRecord {
  id: number;
  associated_project_id?: string | null;
  associated_session_id?: string | null;
  type: string;
  message: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface ComputeTargetRecord {
  id: string;
  pool: string;
  kind: "local";
  label?: string | null;
  status: "idle" | "claimed" | "draining" | "dead";
  claimed_by_task_id?: string | null;
  claimed_at?: string | null;
  last_heartbeat?: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface HarnessHelloParams {
  name?: string;
}

export interface HarnessHelloResult {
  message: string;
  harness?: string;
}

export interface SetupGetParams {
}

export interface SetupGetResult {
  configured: boolean;
  workspace?: WorkspaceRecord | null;
}

export interface SetupCompleteParams {
}

export interface SetupCompleteResult {
  workspace: WorkspaceRecord;
}

export interface SecretsStatusParams {
}

export interface SecretsStatusResult {
  anthropic_key_configured: boolean;
  anthropic_key_source: "local" | "missing";
  logfire_token_configured?: boolean;
  logfire_token_source?: "local" | "missing";
}

export interface SecretsSetAnthropicKeyParams {
  anthropic_key: string;
  logfire_token?: string | null;
}

export interface SecretsSetAnthropicKeyResult {
  anthropic_key_configured?: boolean;
  anthropic_key_source?: "local";
  logfire_token_configured?: boolean;
  logfire_token_source?: "local" | "missing";
}

export interface CollectionsBootstrapParams {
}

export interface CollectionsBootstrapResult {
  cursor: number;
  workspaces?: WorkspaceRecord[];
  projects?: ProjectRecord[];
  sessions: SessionRecord[];
  hypotheses: HypothesisRecord[];
  baselines?: BaselineRecord[];
  experiments: ExperimentRecord[];
  evaluations: EvaluationRecord[];
  measurements?: MeasurementRecord[];
  analyses?: AnalysisRecord[];
  hypothesis_experiment_links: HypothesisExperimentLinkRecord[];
  agents?: AgentRecord[];
  tasks?: TaskRecord[];
  task_dependencies?: TaskDependencyRecord[];
  task_entity_links?: TaskEntityLinkRecord[];
  task_activities?: TaskActivityRecord[];
  analysis_activities?: AnalysisActivityRecord[];
  hypothesis_activities: HypothesisActivityRecord[];
  baseline_activities?: BaselineActivityRecord[];
  experiment_activities: ExperimentActivityRecord[];
  evaluation_activities: EvaluationActivityRecord[];
  artifacts: ArtifactRecord[];
  events: EventRecord[];
  compute_targets?: ComputeTargetRecord[];
}

export interface CollectionsChangesSinceParams {
  cursor: number;
  limit?: number;
}

export interface CollectionsChangesSinceResult {
  changes: CollectionChangeParams[];
  cursor: number;
  has_more?: boolean;
  reset_required?: boolean;
}

export interface CollectionsSubscribeParams {
}

export interface CollectionsSubscribeResult {
  subscribed: boolean;
  cursor: number;
}

export interface CollectionChangeParams {
  cursor: number;
  collection: "workspaces" | "projects" | "sessions" | "hypotheses" | "baselines" | "experiments" | "evaluations" | "measurements" | "analyses" | "hypothesis_experiment_links" | "agents" | "tasks" | "task_dependencies" | "task_entity_links" | "task_activities" | "analysis_activities" | "hypothesis_activities" | "baseline_activities" | "experiment_activities" | "evaluation_activities" | "artifacts" | "events" | "compute_targets";
  key: string;
  op: "upsert" | "delete";
  record?: Record<string, unknown> | null;
  source_event_id?: number | null;
}

export interface CollectionUpsertedParams {
  cursor: number;
  collection: "workspaces" | "projects" | "sessions" | "hypotheses" | "baselines" | "experiments" | "evaluations" | "measurements" | "analyses" | "hypothesis_experiment_links" | "agents" | "tasks" | "task_dependencies" | "task_entity_links" | "task_activities" | "analysis_activities" | "hypothesis_activities" | "baseline_activities" | "experiment_activities" | "evaluation_activities" | "artifacts" | "events" | "compute_targets";
  key: string;
  record: Record<string, unknown>;
  source_event_id?: number | null;
}

export interface EventsSubscribeParams {
  replay_existing?: boolean;
}

export interface EventsSubscribeResult {
  subscribed: boolean;
  replayed?: number;
}

export interface SessionResumeParams {
  session_id: string;
  max_experiments?: number;
}

export interface SessionResumeResult {
  session_id: string;
  status: string;
}

export interface SessionStartParams {
  objective?: string;
  research_context?: string;
  project_title?: string | null;
  project_id?: string | null;
  max_experiments?: number;
}

export interface SessionStartResult {
  session_id: string;
  status: string;
}

export interface SessionStatusParams {
  session_id: string;
}

export interface SessionStatusResult {
  session: SessionRecord | null;
}

export type ControlMethod = "harness.hello" | "setup.get" | "setup.complete" | "secrets.status" | "secrets.set_anthropic_key" | "collections.bootstrap" | "collections.subscribe" | "collections.changes_since" | "events.subscribe" | "session.resume" | "session.start" | "session.status" | "artifacts.read";