// Generated by scripts/generate-protocol.py. Do not edit by hand.

export type JsonRpcId = string | number | null;

export interface JsonRpcErrorObject {
  code: number;
  message: string;
  data?: unknown | null;
}

export interface JsonRpcRequest {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: Record<string, unknown> | null;
}

export interface JsonRpcNotification {
  jsonrpc?: "2.0";
  method: string;
  params?: Record<string, unknown> | null;
}

export interface JsonRpcResponse {
  jsonrpc?: "2.0";
  id?: string | number | null;
  result?: unknown | null;
  error?: JsonRpcErrorObject | null;
}

export interface ProjectConfigRecord {
  id: string;
  repo_path: string;
  goal: string;
  evaluation_context: string;
  known_signals: string[];
  experiment_scope: string;
  created_at: string;
  updated_at: string;
}

export interface RunRecord {
  id: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface ExperimentRecord {
  id: string;
  run_id: string;
  status: string;
  intent: string;
  change_summary: string;
  components: string[];
  based_on: string[];
  suspicious?: boolean;
  suspicious_reason?: string | null;
  note?: string;
  created_at: string;
  updated_at: string;
}

export interface SignalRecord {
  key: string;
  value: unknown;
  unit?: string | null;
}

export interface EvidenceRecord {
  id: number;
  run_id: string;
  experiment_id: string;
  summary: string;
  signals: SignalRecord[];
  raw: Record<string, unknown>;
  created_at: string;
}

export interface FindingRecord {
  id: string;
  run_id: string;
  summary: string;
  evidence_experiment_ids: string[];
  confidence: "low" | "medium" | "high";
  status: "open" | "supported" | "contradicted";
  created_at: string;
  updated_at: string;
}

export interface WarningRecord {
  id: number;
  run_id: string;
  experiment_id?: string | null;
  kind: string;
  message: string;
  created_at: string;
}

export interface EventRecord {
  id: number;
  run_id?: string | null;
  type: string;
  message: string;
  payload: Record<string, unknown>;
  created_at: string;
}

export interface HarnessHelloParams {
  name?: string;
}

export interface HarnessHelloResult {
  message: string;
  harness?: string;
}

export interface SetupGetParams {
}

export interface SetupGetResult {
  configured: boolean;
  config?: ProjectConfigRecord | null;
}

export interface SetupCompleteParams {
  goal: string;
  evaluation_context: string;
  known_signals?: string[];
  experiment_scope?: string;
}

export interface SetupCompleteResult {
  config: ProjectConfigRecord;
}

export interface CollectionsBootstrapParams {
}

export interface CollectionsBootstrapResult {
  cursor: number;
  runs: RunRecord[];
  experiments: ExperimentRecord[];
  events: EventRecord[];
}

export interface CollectionsSubscribeParams {
}

export interface CollectionsSubscribeResult {
  subscribed: boolean;
  cursor: number;
}

export interface CollectionUpsertedParams {
  cursor: number;
  collection: "runs" | "experiments" | "events";
  key: string;
  record: Record<string, unknown>;
}

export interface EventsSubscribeParams {
  replay_existing?: boolean;
}

export interface EventsSubscribeResult {
  subscribed: boolean;
  replayed?: number;
}

export interface RunStartParams {
  max_experiments?: number;
}

export interface RunStartResult {
  run_id: string;
  status: string;
}

export interface RunStatusParams {
  run_id: string;
}

export interface RunStatusResult {
  run: RunRecord | null;
}

export interface WorkerInitializeParams {
  protocol_version?: number;
}

export interface WorkerInitializeResult {
  worker_name: string;
  protocol_version?: number;
}

export interface ExperimentRunParams {
  run_id: string;
  experiment_id: string;
  intent: string;
  components: string[];
  based_on?: string[];
}

export interface ExperimentRunResult {
  experiment_id: string;
  status: string;
  summary: string;
  signals: SignalRecord[];
  raw: Record<string, unknown>;
}

export interface WorkerProgressParams {
  run_id: string;
  experiment_id: string;
  message: string;
  payload?: Record<string, unknown>;
}

export type ControlMethod = "harness.hello" | "setup.get" | "setup.complete" | "collections.bootstrap" | "collections.subscribe" | "events.subscribe" | "run.start" | "run.status";
export type WorkerMethod = "worker.initialize" | "experiment.run";
