// Generated by scripts/generate-protocol.py. Do not edit by hand.

export type JsonRpcId = string | number | null;

export interface JsonRpcErrorObject {
  code: number;
  message: string;
  data?: unknown | null;
}

export interface JsonRpcRequest {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: Record<string, unknown> | null;
}

export interface JsonRpcNotification {
  jsonrpc?: "2.0";
  method: string;
  params?: Record<string, unknown> | null;
}

export interface JsonRpcResponse {
  jsonrpc?: "2.0";
  id?: string | number | null;
  result?: unknown | null;
  error?: JsonRpcErrorObject | null;
}

export interface ProjectRecord {
  id: string;
  repo_path: string;
  created_at: string;
  updated_at: string;
}

export interface ObjectiveRecord {
  id: string;
  session_id: string;
  title: string;
  description: string;
  status: "active" | "closed";
  created_at: string;
  updated_at: string;
}

export interface ResearchContextRecord {
  id: string;
  session_id: string;
  body: string;
  created_at: string;
  updated_at: string;
}

export interface SessionRecord {
  id: string;
  project_id: string;
  status: "active" | "closed";
  created_at: string;
  updated_at: string;
}

export interface HypothesisRecord {
  id: string;
  session_id: string;
  title: string;
  summary: string;
  status: "open" | "active" | "closed";
  created_at: string;
  updated_at: string;
}

export interface ExperimentRecord {
  id: string;
  session_id: string;
  status: "open" | "active" | "closed";
  title: string;
  summary: string;
  created_at: string;
  updated_at: string;
}

export interface EvaluationRecord {
  id: string;
  session_id: string;
  status: "open" | "active" | "closed";
  title: string;
  summary: string;
  associated_experiment_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface HypothesisExperimentLinkRecord {
  hypothesis_id: string;
  experiment_id: string;
  created_at: string;
}

export interface HypothesisActivityRecord {
  id: number;
  hypothesis_id: string;
  actor: string;
  kind: "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface ExperimentActivityRecord {
  id: number;
  experiment_id: string;
  actor: string;
  kind: "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface EvaluationActivityRecord {
  id: number;
  evaluation_id: string;
  actor: string;
  kind: "comment";
  body: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface ArtifactRecord {
  id: string;
  session_id: string;
  associated_entity_kind: string;
  associated_entity_id: string;
  kind: string;
  title: string;
  path: string;
  media_type?: string | null;
  size_bytes?: number | null;
  created_at: string;
}

export interface EventRecord {
  id: number;
  session_id?: string | null;
  type: string;
  message: string;
  payload?: Record<string, unknown>;
  created_at: string;
}

export interface HarnessHelloParams {
  name?: string;
}

export interface HarnessHelloResult {
  message: string;
  harness?: string;
}

export interface SetupGetParams {
}

export interface SetupGetResult {
  configured: boolean;
  project?: ProjectRecord | null;
}

export interface SetupCompleteParams {
}

export interface SetupCompleteResult {
  project: ProjectRecord;
}

export interface CollectionsBootstrapParams {
}

export interface CollectionsBootstrapResult {
  cursor: number;
  projects: ProjectRecord[];
  objectives: ObjectiveRecord[];
  research_contexts: ResearchContextRecord[];
  sessions: SessionRecord[];
  hypotheses: HypothesisRecord[];
  experiments: ExperimentRecord[];
  evaluations: EvaluationRecord[];
  hypothesis_experiment_links: HypothesisExperimentLinkRecord[];
  hypothesis_activities: HypothesisActivityRecord[];
  experiment_activities: ExperimentActivityRecord[];
  evaluation_activities: EvaluationActivityRecord[];
  artifacts: ArtifactRecord[];
  events: EventRecord[];
}

export interface CollectionsSubscribeParams {
}

export interface CollectionsSubscribeResult {
  subscribed: boolean;
  cursor: number;
}

export interface CollectionUpsertedParams {
  cursor: number;
  collection: "projects" | "objectives" | "research_contexts" | "sessions" | "hypotheses" | "experiments" | "evaluations" | "hypothesis_experiment_links" | "hypothesis_activities" | "experiment_activities" | "evaluation_activities" | "artifacts" | "events";
  key: string;
  record: Record<string, unknown>;
}

export interface EventsSubscribeParams {
  replay_existing?: boolean;
}

export interface EventsSubscribeResult {
  subscribed: boolean;
  replayed?: number;
}

export interface SessionResumeParams {
  session_id: string;
  max_experiments?: number;
}

export interface SessionResumeResult {
  session_id: string;
  status: string;
}

export interface SessionStartParams {
  objective: string;
  research_context: string;
  max_experiments?: number;
}

export interface SessionStartResult {
  session_id: string;
  status: string;
}

export interface SessionStatusParams {
  session_id: string;
}

export interface SessionStatusResult {
  session: SessionRecord | null;
}

export interface WorkerInitializeParams {
  protocol_version?: number;
}

export interface WorkerInitializeResult {
  worker_name: string;
  protocol_version?: number;
}

export interface ExperimentRunParams {
  session_id: string;
  experiment_id: string;
  title: string;
  summary: string;
  components?: string[];
  based_on?: string[];
}

export interface ExperimentRunResult {
  experiment_id: string;
  status: string;
  summary: string;
  signals?: Record<string, unknown>[];
  raw?: Record<string, unknown>;
}

export interface WorkerProgressParams {
  session_id: string;
  experiment_id: string;
  message: string;
  payload?: Record<string, unknown>;
}

export type ControlMethod = "harness.hello" | "setup.get" | "setup.complete" | "collections.bootstrap" | "collections.subscribe" | "events.subscribe" | "session.resume" | "session.start" | "session.status";
export type WorkerMethod = "worker.initialize" | "experiment.run";
