import { createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract(
  {
    color: {
      background: "background",
      foreground: "foreground",
      panel: "panel",
      stage: "stage",
      cardHex: "card-hex",
      card01Hex: "card-01-hex",
      card02Hex: "card-02-hex",
      card03Hex: "card-03-hex",
      fg05: "fg-05",
      fg07_5: "fg-07-5",
      fg10: "fg-10",
      border: "border",
      border01_5: "border-01-5",
      border02: "border-02",
      border02_5: "border-02-5",
      border03: "border-03",
      borderSubtle: "border-subtle",
      surfaceHover: "surface-hover",
      mutedForeground: "muted-foreground",
      mutedForegroundTertiary: "muted-foreground-tertiary",
      accent: "accent",
      primary: "primary",
      primaryForeground: "primary-foreground",
      primaryHover: "primary-hover",
      ring: "ring",
      successStrong: "success-strong",
      successSoft: "success-soft",
      dangerStrong: "danger-strong",
      dangerSoft: "danger-soft",
      warningStrong: "warning-strong",
      warningSoft: "warning-soft",
      badgeGray: "badge-gray",
      badgeGrayText: "badge-gray-text",
      badgeGreen: "badge-green",
      badgeGreenText: "badge-green-text",
      badgeRed: "badge-red",
      badgeRedText: "badge-red-text",
      badgeYellow: "badge-yellow",
      badgeYellowText: "badge-yellow-text",
      badgeBlue: "badge-blue",
      badgeBlueText: "badge-blue-text",
      badgePurple: "badge-purple",
      badgePurpleText: "badge-purple-text",
    },
    font: {
      sans: "font-sans",
      mono: "font-mono",
    },
    text: {
      productSm: "text-product-sm",
      productBase: "text-product-base",
      productLg: "text-product-lg",
      body: "text-body",
      displaySm: "text-display-sm",
      displayMd: "text-display-md",
      displayLg: "text-display-lg",
    },
    leading: {
      productSm: "leading-product-sm",
      productBase: "leading-product-base",
      body: "leading-body",
    },
    tracking: {
      productSm: "tracking-product-sm",
      display: "tracking-display",
    },
    radius: {
      sm: "radius-sm",
      md: "radius-md",
      lg: "radius-lg",
      xl: "radius-xl",
    },
    shadow: {
      window: "shadow-window",
      card: "shadow-card",
    },
  },
  (value) => value as string,
);
