"""Tests that guard the meta layer (specs, policies, generated protocol).

Per policy 0027-convention-policy-coverage and the audit-policies skill,
these are mechanizable checks on the .agents/ surface and the generated
TypeScript protocol artifact. They prevent the kind of drift that erodes
the spec/policy contract over time.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SPECS_DIR = REPO_ROOT / ".agents" / "specs"
POLICIES_DIR = REPO_ROOT / ".agents" / "policies"
GENERATED_TS = REPO_ROOT / "shared" / "typescript" / "protocol" / "src" / "generated.ts"

# Phrases that signal future-tense process language inside specs.
# Per policy 0033-specs-as-end-state, specs describe the running system,
# not the work to build it. These phrases get past review easily and
# silently rot the contract.
FUTURE_TENSE_PHRASES = (
    "should converge",
    "for now",
    "moving toward",
    "first slice",
    "later slice",
)

# Specific specs may legitimately use a phrase in a different sense
# (e.g., describing a non-goal). Allow narrow exemptions per (file_stem,
# phrase) — kept here so each one is visible and reviewable.
FUTURE_TENSE_EXEMPTIONS: set[tuple[str, str]] = set()


def test_specs_avoid_future_tense_process_language() -> None:
    """Per policy 0033-specs-as-end-state, specs describe what the system
    is, not what it will become. Catches recurring drift like 'should
    converge', 'first slice / later slice', 'for now', 'moving toward'."""
    spec_files = sorted(SPECS_DIR.glob("*/SPEC.md"))
    assert spec_files, "expected SPEC.md files under .agents/specs/*/"
    violations: list[str] = []
    for spec_path in spec_files:
        text = spec_path.read_text().lower()
        spec_stem = spec_path.parent.name
        for phrase in FUTURE_TENSE_PHRASES:
            if phrase in text and (spec_stem, phrase) not in FUTURE_TENSE_EXEMPTIONS:
                violations.append(
                    f"{spec_path.relative_to(REPO_ROOT)} contains future-tense "
                    f"phrase {phrase!r}"
                )
    assert not violations, "\n".join(violations)


def test_spec_readme_index_synced_with_dirs() -> None:
    """The spec README index must list exactly the specs that exist on
    disk. Catches new specs that ship without an index entry, and stale
    entries pointing at removed specs."""
    readme = (SPECS_DIR / "README.md").read_text()
    on_disk = {p.parent.name for p in SPECS_DIR.glob("*/SPEC.md")}
    indexed = set(re.findall(r"\(\./([0-9]{4}-[a-z0-9-]+)/SPEC\.md\)", readme))
    assert on_disk == indexed, (
        f"spec index drift:\n  on disk but not indexed: {sorted(on_disk - indexed)}\n"
        f"  indexed but not on disk: {sorted(indexed - on_disk)}"
    )


def test_policy_index_synced_with_dirs() -> None:
    """The policy DOC index must list exactly the policies that exist on
    disk."""
    doc = (POLICIES_DIR / "DOC.md").read_text()
    on_disk = {p.parent.name for p in POLICIES_DIR.glob("*/POLICY.md")}
    indexed = set(re.findall(r"\(\./([0-9]{4}-[a-z0-9-]+)/POLICY\.md\)", doc))
    assert on_disk == indexed, (
        f"policy index drift:\n  on disk but not indexed: {sorted(on_disk - indexed)}\n"
        f"  indexed but not on disk: {sorted(indexed - on_disk)}"
    )


def test_policies_have_frontmatter() -> None:
    """Every POLICY.md carries the standard YAML frontmatter with title
    and status fields. Per the situ-spec-policy-maintenance skill."""
    for policy_path in sorted(POLICIES_DIR.glob("*/POLICY.md")):
        text = policy_path.read_text()
        assert text.startswith("---\n"), (
            f"{policy_path.relative_to(REPO_ROOT)} missing frontmatter opener"
        )
        # Frontmatter ends at the second '---' line.
        try:
            frontmatter_end = text.index("\n---\n", 4)
        except ValueError as error:
            raise AssertionError(
                f"{policy_path.relative_to(REPO_ROOT)} frontmatter is unterminated"
            ) from error
        frontmatter = text[4:frontmatter_end]
        assert "title:" in frontmatter, (
            f"{policy_path.relative_to(REPO_ROOT)} missing title in frontmatter"
        )
        assert "status:" in frontmatter, (
            f"{policy_path.relative_to(REPO_ROOT)} missing status in frontmatter"
        )


def test_protocol_generated_typescript_is_readonly() -> None:
    """`shared/typescript/protocol/src/generated.ts` is generated by
    scripts/generate-protocol.py. The first line carries a do-not-edit
    marker; this test asserts the marker is present so a hand-edit that
    removed it would be caught."""
    if not GENERATED_TS.is_file():
        pytest.skip("generated.ts not present; run protocol-generate")
    first_line = GENERATED_TS.read_text().splitlines()[0]
    assert "Generated by" in first_line, (
        "generated.ts is missing the 'Generated by ...' marker — was it "
        "hand-edited or regenerated by a different script?"
    )
    assert "Do not edit" in first_line, (
        "generated.ts is missing the 'Do not edit' marker"
    )
