from __future__ import annotations

import json
import types
from enum import StrEnum
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel

from almanac.protocol import (
    ArtifactRecord,
    CollectionUpsertedParams,
    CollectionsBootstrapParams,
    CollectionsBootstrapResult,
    CollectionsSubscribeParams,
    CollectionsSubscribeResult,
    EventRecord,
    EvaluationActivityRecord,
    EvaluationRecord,
    EventsSubscribeParams,
    EventsSubscribeResult,
    ExperimentActivityRecord,
    ExperimentRecord,
    ExperimentRunParams,
    ExperimentRunResult,
    HarnessHelloParams,
    HarnessHelloResult,
    HypothesisActivityRecord,
    HypothesisExperimentLinkRecord,
    HypothesisRecord,
    JsonRpcErrorObject,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    ObjectiveRecord,
    ProjectConfigRecord,
    SessionRecord,
    SessionResumeParams,
    SessionResumeResult,
    SessionStartParams,
    SessionStartResult,
    SessionStatusParams,
    SessionStatusResult,
    SetupCompleteParams,
    SetupCompleteResult,
    SetupGetParams,
    SetupGetResult,
    WorkerInitializeParams,
    WorkerInitializeResult,
    WorkerProgressParams,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = REPO_ROOT / "protocol" / "json-schema"
TS_OUTPUT = REPO_ROOT / "shared" / "typescript" / "protocol" / "src" / "generated.ts"

MODELS: list[type[BaseModel]] = [
    JsonRpcErrorObject,
    JsonRpcRequest,
    JsonRpcNotification,
    JsonRpcResponse,
    ProjectConfigRecord,
    ObjectiveRecord,
    SessionRecord,
    HypothesisRecord,
    ExperimentRecord,
    EvaluationRecord,
    HypothesisExperimentLinkRecord,
    HypothesisActivityRecord,
    ExperimentActivityRecord,
    EvaluationActivityRecord,
    ArtifactRecord,
    EventRecord,
    HarnessHelloParams,
    HarnessHelloResult,
    SetupGetParams,
    SetupGetResult,
    SetupCompleteParams,
    SetupCompleteResult,
    CollectionsBootstrapParams,
    CollectionsBootstrapResult,
    CollectionsSubscribeParams,
    CollectionsSubscribeResult,
    CollectionUpsertedParams,
    EventsSubscribeParams,
    EventsSubscribeResult,
    SessionResumeParams,
    SessionResumeResult,
    SessionStartParams,
    SessionStartResult,
    SessionStatusParams,
    SessionStatusResult,
    WorkerInitializeParams,
    WorkerInitializeResult,
    ExperimentRunParams,
    ExperimentRunResult,
    WorkerProgressParams,
]


def write_json_schemas() -> None:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    for model in MODELS:
        path = SCHEMA_DIR / f"{kebab_case(model.__name__)}.schema.json"
        path.write_text(json.dumps(model.model_json_schema(), indent=2) + "\n")


def generate_typescript() -> str:
    lines = [
        "// Generated by scripts/generate-protocol.py. Do not edit by hand.",
        "",
        "export type JsonRpcId = string | number | null;",
        "",
    ]
    for model in MODELS:
        lines.append(render_interface(model))
        lines.append("")
    lines.extend(
        [
            'export type ControlMethod = "harness.hello" | "setup.get" | "setup.complete" | "collections.bootstrap" | "collections.subscribe" | "events.subscribe" | "session.resume" | "session.start" | "session.status";',
            'export type WorkerMethod = "worker.initialize" | "experiment.run";',
            "",
        ]
    )
    return "\n".join(lines)


def render_interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        optional = "?" if not field.is_required() else ""
        lines.append(f"  {name}{optional}: {ts_type(field.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def ts_type(annotation: object) -> str:
    if annotation is Any:
        return "unknown"
    if annotation is str:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is None or annotation is types.NoneType:
        return "null"
    if isinstance(annotation, type) and issubclass(annotation, StrEnum):
        return " | ".join(json.dumps(item.value) for item in annotation)

    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin is Literal:
        return " | ".join(json.dumps(value) for value in args)
    if origin is list:
        return f"{ts_type(args[0])}[]"
    if origin is dict:
        value_type = ts_type(args[1]) if len(args) == 2 else "unknown"
        return f"Record<string, {value_type}>"
    if origin in {types.UnionType, getattr(types, "UnionType", None)} or str(origin) == "typing.Union":
        return " | ".join(ts_type(arg) for arg in args)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    return "unknown"


def kebab_case(value: str) -> str:
    chars: list[str] = []
    for index, char in enumerate(value):
        if char.isupper() and index > 0:
            chars.append("-")
        chars.append(char.lower())
    return "".join(chars)


def main() -> None:
    write_json_schemas()
    TS_OUTPUT.write_text(generate_typescript())


if __name__ == "__main__":
    main()
