/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkItemsRouteImport } from "./routes/work-items";
import { Route as ProjectRouteImport } from "./routes/project";
import { Route as MeasurementsRouteImport } from "./routes/measurements";
import { Route as FeedRouteImport } from "./routes/feed";
import { Route as EntityLinksRouteImport } from "./routes/entity-links";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ArtifactsRouteImport } from "./routes/artifacts";
import { Route as AgentsRouteImport } from "./routes/agents";
import { Route as ActivitiesRouteImport } from "./routes/activities";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as HypothesesIndexRouteImport } from "./routes/hypotheses/index";
import { Route as ExperimentsIndexRouteImport } from "./routes/experiments/index";
import { Route as EvaluationsIndexRouteImport } from "./routes/evaluations/index";
import { Route as BaselinesIndexRouteImport } from "./routes/baselines/index";
import { Route as HypothesesHypothesisIdRouteImport } from "./routes/hypotheses/$hypothesisId";
import { Route as ExperimentsExperimentIdRouteImport } from "./routes/experiments/$experimentId";
import { Route as EvaluationsEvaluationIdRouteImport } from "./routes/evaluations/$evaluationId";
import { Route as BaselinesBaselineIdRouteImport } from "./routes/baselines/$baselineId";

const WorkItemsRoute = WorkItemsRouteImport.update({
  id: "/work-items",
  path: "/work-items",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectRoute = ProjectRouteImport.update({
  id: "/project",
  path: "/project",
  getParentRoute: () => rootRouteImport,
} as any);
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: "/measurements",
  path: "/measurements",
  getParentRoute: () => rootRouteImport,
} as any);
const FeedRoute = FeedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => rootRouteImport,
} as any);
const EntityLinksRoute = EntityLinksRouteImport.update({
  id: "/entity-links",
  path: "/entity-links",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: "/artifacts",
  path: "/artifacts",
  getParentRoute: () => rootRouteImport,
} as any);
const AgentsRoute = AgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: "/activities",
  path: "/activities",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const HypothesesIndexRoute = HypothesesIndexRouteImport.update({
  id: "/hypotheses/",
  path: "/hypotheses/",
  getParentRoute: () => rootRouteImport,
} as any);
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: "/experiments/",
  path: "/experiments/",
  getParentRoute: () => rootRouteImport,
} as any);
const EvaluationsIndexRoute = EvaluationsIndexRouteImport.update({
  id: "/evaluations/",
  path: "/evaluations/",
  getParentRoute: () => rootRouteImport,
} as any);
const BaselinesIndexRoute = BaselinesIndexRouteImport.update({
  id: "/baselines/",
  path: "/baselines/",
  getParentRoute: () => rootRouteImport,
} as any);
const HypothesesHypothesisIdRoute = HypothesesHypothesisIdRouteImport.update({
  id: "/hypotheses/$hypothesisId",
  path: "/hypotheses/$hypothesisId",
  getParentRoute: () => rootRouteImport,
} as any);
const ExperimentsExperimentIdRoute = ExperimentsExperimentIdRouteImport.update({
  id: "/experiments/$experimentId",
  path: "/experiments/$experimentId",
  getParentRoute: () => rootRouteImport,
} as any);
const EvaluationsEvaluationIdRoute = EvaluationsEvaluationIdRouteImport.update({
  id: "/evaluations/$evaluationId",
  path: "/evaluations/$evaluationId",
  getParentRoute: () => rootRouteImport,
} as any);
const BaselinesBaselineIdRoute = BaselinesBaselineIdRouteImport.update({
  id: "/baselines/$baselineId",
  path: "/baselines/$baselineId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/activities": typeof ActivitiesRoute;
  "/agents": typeof AgentsRoute;
  "/artifacts": typeof ArtifactsRoute;
  "/dashboard": typeof DashboardRoute;
  "/entity-links": typeof EntityLinksRoute;
  "/feed": typeof FeedRoute;
  "/measurements": typeof MeasurementsRoute;
  "/project": typeof ProjectRoute;
  "/work-items": typeof WorkItemsRoute;
  "/baselines/$baselineId": typeof BaselinesBaselineIdRoute;
  "/evaluations/$evaluationId": typeof EvaluationsEvaluationIdRoute;
  "/experiments/$experimentId": typeof ExperimentsExperimentIdRoute;
  "/hypotheses/$hypothesisId": typeof HypothesesHypothesisIdRoute;
  "/baselines/": typeof BaselinesIndexRoute;
  "/evaluations/": typeof EvaluationsIndexRoute;
  "/experiments/": typeof ExperimentsIndexRoute;
  "/hypotheses/": typeof HypothesesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/activities": typeof ActivitiesRoute;
  "/agents": typeof AgentsRoute;
  "/artifacts": typeof ArtifactsRoute;
  "/dashboard": typeof DashboardRoute;
  "/entity-links": typeof EntityLinksRoute;
  "/feed": typeof FeedRoute;
  "/measurements": typeof MeasurementsRoute;
  "/project": typeof ProjectRoute;
  "/work-items": typeof WorkItemsRoute;
  "/baselines/$baselineId": typeof BaselinesBaselineIdRoute;
  "/evaluations/$evaluationId": typeof EvaluationsEvaluationIdRoute;
  "/experiments/$experimentId": typeof ExperimentsExperimentIdRoute;
  "/hypotheses/$hypothesisId": typeof HypothesesHypothesisIdRoute;
  "/baselines": typeof BaselinesIndexRoute;
  "/evaluations": typeof EvaluationsIndexRoute;
  "/experiments": typeof ExperimentsIndexRoute;
  "/hypotheses": typeof HypothesesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/activities": typeof ActivitiesRoute;
  "/agents": typeof AgentsRoute;
  "/artifacts": typeof ArtifactsRoute;
  "/dashboard": typeof DashboardRoute;
  "/entity-links": typeof EntityLinksRoute;
  "/feed": typeof FeedRoute;
  "/measurements": typeof MeasurementsRoute;
  "/project": typeof ProjectRoute;
  "/work-items": typeof WorkItemsRoute;
  "/baselines/$baselineId": typeof BaselinesBaselineIdRoute;
  "/evaluations/$evaluationId": typeof EvaluationsEvaluationIdRoute;
  "/experiments/$experimentId": typeof ExperimentsExperimentIdRoute;
  "/hypotheses/$hypothesisId": typeof HypothesesHypothesisIdRoute;
  "/baselines/": typeof BaselinesIndexRoute;
  "/evaluations/": typeof EvaluationsIndexRoute;
  "/experiments/": typeof ExperimentsIndexRoute;
  "/hypotheses/": typeof HypothesesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/activities"
    | "/agents"
    | "/artifacts"
    | "/dashboard"
    | "/entity-links"
    | "/feed"
    | "/measurements"
    | "/project"
    | "/work-items"
    | "/baselines/$baselineId"
    | "/evaluations/$evaluationId"
    | "/experiments/$experimentId"
    | "/hypotheses/$hypothesisId"
    | "/baselines/"
    | "/evaluations/"
    | "/experiments/"
    | "/hypotheses/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/activities"
    | "/agents"
    | "/artifacts"
    | "/dashboard"
    | "/entity-links"
    | "/feed"
    | "/measurements"
    | "/project"
    | "/work-items"
    | "/baselines/$baselineId"
    | "/evaluations/$evaluationId"
    | "/experiments/$experimentId"
    | "/hypotheses/$hypothesisId"
    | "/baselines"
    | "/evaluations"
    | "/experiments"
    | "/hypotheses";
  id:
    | "__root__"
    | "/"
    | "/activities"
    | "/agents"
    | "/artifacts"
    | "/dashboard"
    | "/entity-links"
    | "/feed"
    | "/measurements"
    | "/project"
    | "/work-items"
    | "/baselines/$baselineId"
    | "/evaluations/$evaluationId"
    | "/experiments/$experimentId"
    | "/hypotheses/$hypothesisId"
    | "/baselines/"
    | "/evaluations/"
    | "/experiments/"
    | "/hypotheses/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ActivitiesRoute: typeof ActivitiesRoute;
  AgentsRoute: typeof AgentsRoute;
  ArtifactsRoute: typeof ArtifactsRoute;
  DashboardRoute: typeof DashboardRoute;
  EntityLinksRoute: typeof EntityLinksRoute;
  FeedRoute: typeof FeedRoute;
  MeasurementsRoute: typeof MeasurementsRoute;
  ProjectRoute: typeof ProjectRoute;
  WorkItemsRoute: typeof WorkItemsRoute;
  BaselinesBaselineIdRoute: typeof BaselinesBaselineIdRoute;
  EvaluationsEvaluationIdRoute: typeof EvaluationsEvaluationIdRoute;
  ExperimentsExperimentIdRoute: typeof ExperimentsExperimentIdRoute;
  HypothesesHypothesisIdRoute: typeof HypothesesHypothesisIdRoute;
  BaselinesIndexRoute: typeof BaselinesIndexRoute;
  EvaluationsIndexRoute: typeof EvaluationsIndexRoute;
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute;
  HypothesesIndexRoute: typeof HypothesesIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/work-items": {
      id: "/work-items";
      path: "/work-items";
      fullPath: "/work-items";
      preLoaderRoute: typeof WorkItemsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project": {
      id: "/project";
      path: "/project";
      fullPath: "/project";
      preLoaderRoute: typeof ProjectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/measurements": {
      id: "/measurements";
      path: "/measurements";
      fullPath: "/measurements";
      preLoaderRoute: typeof MeasurementsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/feed": {
      id: "/feed";
      path: "/feed";
      fullPath: "/feed";
      preLoaderRoute: typeof FeedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/entity-links": {
      id: "/entity-links";
      path: "/entity-links";
      fullPath: "/entity-links";
      preLoaderRoute: typeof EntityLinksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/artifacts": {
      id: "/artifacts";
      path: "/artifacts";
      fullPath: "/artifacts";
      preLoaderRoute: typeof ArtifactsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof AgentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/activities": {
      id: "/activities";
      path: "/activities";
      fullPath: "/activities";
      preLoaderRoute: typeof ActivitiesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/hypotheses/": {
      id: "/hypotheses/";
      path: "/hypotheses";
      fullPath: "/hypotheses/";
      preLoaderRoute: typeof HypothesesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/experiments/": {
      id: "/experiments/";
      path: "/experiments";
      fullPath: "/experiments/";
      preLoaderRoute: typeof ExperimentsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/evaluations/": {
      id: "/evaluations/";
      path: "/evaluations";
      fullPath: "/evaluations/";
      preLoaderRoute: typeof EvaluationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/baselines/": {
      id: "/baselines/";
      path: "/baselines";
      fullPath: "/baselines/";
      preLoaderRoute: typeof BaselinesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/hypotheses/$hypothesisId": {
      id: "/hypotheses/$hypothesisId";
      path: "/hypotheses/$hypothesisId";
      fullPath: "/hypotheses/$hypothesisId";
      preLoaderRoute: typeof HypothesesHypothesisIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/experiments/$experimentId": {
      id: "/experiments/$experimentId";
      path: "/experiments/$experimentId";
      fullPath: "/experiments/$experimentId";
      preLoaderRoute: typeof ExperimentsExperimentIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/evaluations/$evaluationId": {
      id: "/evaluations/$evaluationId";
      path: "/evaluations/$evaluationId";
      fullPath: "/evaluations/$evaluationId";
      preLoaderRoute: typeof EvaluationsEvaluationIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/baselines/$baselineId": {
      id: "/baselines/$baselineId";
      path: "/baselines/$baselineId";
      fullPath: "/baselines/$baselineId";
      preLoaderRoute: typeof BaselinesBaselineIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AgentsRoute: AgentsRoute,
  ArtifactsRoute: ArtifactsRoute,
  DashboardRoute: DashboardRoute,
  EntityLinksRoute: EntityLinksRoute,
  FeedRoute: FeedRoute,
  MeasurementsRoute: MeasurementsRoute,
  ProjectRoute: ProjectRoute,
  WorkItemsRoute: WorkItemsRoute,
  BaselinesBaselineIdRoute: BaselinesBaselineIdRoute,
  EvaluationsEvaluationIdRoute: EvaluationsEvaluationIdRoute,
  ExperimentsExperimentIdRoute: ExperimentsExperimentIdRoute,
  HypothesesHypothesisIdRoute: HypothesesHypothesisIdRoute,
  BaselinesIndexRoute: BaselinesIndexRoute,
  EvaluationsIndexRoute: EvaluationsIndexRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
  HypothesesIndexRoute: HypothesesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
