import {
  baselineActivityRecord,
  evaluationActivityRecord,
  experimentActivityRecord,
  hypothesisActivityRecord,
} from "./activity-records";
import {
  feedEntryRecord,
  researchProjectInteractionRecord,
  researchProjectRecord,
  researchTaskRecord,
  researchTaskVerificationRecord,
  workItemRecord,
} from "./research-records";
import {
  appEventRecord,
  claudeAgentEnvironmentRecord,
  claudeAgentEventRecord,
  claudeAgentRecord,
  claudeAgentRunRecord,
  computeTargetRecord,
  localSettingsRecord,
  runtimeStatusRecord,
  sessionRecord,
} from "./runtime-records";
import {
  artifactRecord,
  baselineRecord,
  entityLinkRecord,
  evaluationRecord,
  experimentRecord,
  hypothesisRecord,
  measurementRecord,
} from "./science-records";

export const replicacheRecord = {
  session: sessionRecord,
  localSettings: localSettingsRecord,
  claudeAgent: claudeAgentRecord,
  claudeAgentEnvironment: claudeAgentEnvironmentRecord,
  claudeAgentRun: claudeAgentRunRecord,
  claudeAgentEvent: claudeAgentEventRecord,
  appEvent: appEventRecord,
  researchProject: researchProjectRecord,
  researchProjectInteraction: researchProjectInteractionRecord,
  feedEntry: feedEntryRecord,
  researchTask: researchTaskRecord,
  researchTaskVerification: researchTaskVerificationRecord,
  workItem: workItemRecord,
  hypothesis: hypothesisRecord,
  experiment: experimentRecord,
  baseline: baselineRecord,
  evaluation: evaluationRecord,
  measurement: measurementRecord,
  artifact: artifactRecord,
  entityLink: entityLinkRecord,
  hypothesisActivity: hypothesisActivityRecord,
  experimentActivity: experimentActivityRecord,
  baselineActivity: baselineActivityRecord,
  evaluationActivity: evaluationActivityRecord,
  computeTarget: computeTargetRecord,
  runtimeStatus: runtimeStatusRecord,
} as const;
